version: '3.4'

services:
  speech2notes:
    image: speech2notes
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app.py "]
    ports:
      - 5678:5678