version: '3.4'

services:
  speech2notes:
    image: speech2notes
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OPENAI_API_KEY=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
      - TELEGRAM_TOKEN=7025545038:AAE8erqS3PKGEG-t0orCQxm84h6yaA0DRw4
